fix issue with `superagent` initialization
fix the following issue:

```text
SwaggerTest.ts(432,40): error TS2345: Argument of type '{ default: SuperAgentStatic; agent(): SuperAgentStatic & Request; serialize: { [type: string]: Serializer; }; parse: { [type: string]: Parser; }; jar: CookieJar; attachCookies(req: SuperAgentRequest): void; ... 26 more ...; unsubscribe(url: string, callback?: CallbackHandler | undefined): SuperAgentRequest; }' is not assignable to parameter of type 'SuperAgentStatic'.
  Type '{ default: SuperAgentStatic; agent(): SuperAgentStatic & Request; serialize: { [type: string]: Serializer; }; parse: { [type: string]: Parser; }; jar: CookieJar; attachCookies(req: SuperAgentRequest): void; ... 26 more ...; unsubscribe(url: string, callback?: CallbackHandler | undefined): SuperAgentRequest; }' is missing the following properties from type 'SuperAgentStatic': pipe, addListener, on, once, and 12 more.
```

by using `request.default`.